name: Question
description: Ask a question about the Claude API Demos
title: "[QUESTION] "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the Claude API Demos? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Setup and Installation
        - Demo Usage
        - API Configuration
        - Development and Contributing
        - VS Code Integration
        - Package Usage
        - General Claude API
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about what you're trying to accomplish
      placeholder: What are you trying to do? What have you tried so far?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: If your question is about setup or technical issues, please provide environment info
      value: |
        - OS: [e.g. Windows 11, macOS 12.0, Ubuntu 20.04]
        - Python Version: [e.g. 3.9.7]
        - Package Version: [e.g. 1.0.0]
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the existing documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true
