name: Code Quality
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy bandit safety
          pip install -e .

      - name: Run Black formatter check
        run: |
          black --check --diff src/ tests/

      - name: Run isort import sorting check
        run: |
          isort --check-only --diff src/ tests/

      - name: Run Flake8 linting
        run: |
          flake8 src/ tests/ --max-line-length=88 \
            --extend-ignore=E203,W503 \
            --exclude=__pycache__,*.egg-info

      - name: Run MyPy type checking
        run: |
          mypy src/claude_api_demos/ --ignore-missing-imports || true

      - name: Run Bandit security check
        run: |
          bandit -r src/ -f json || true

      - name: Run Safety dependency check
        run: |
          safety check || true

      - name: Check for common issues
        run: |
          # Check for TODO/FIXME comments
          echo "Checking for TODO/FIXME comments:"
          grep -r "TODO\|FIXME" src/ tests/ || echo "No TODO/FIXME found"

          # Check for print statements (should use logging)
          echo "Checking for print statements:"
          grep -r "print(" src/ --exclude-dir=__pycache__ || echo "No print statements found"

          # Check for hardcoded secrets patterns
          echo "Checking for potential secrets:"
          grep -r -i "api[_-]key\|password\|secret" src/ tests/ --exclude-dir=__pycache__ || echo "No potential secrets found"
