name: Dependency Update
on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Create requirements.in if not exists
        run: |
          if [ ! -f requirements.in ]; then
            cat > requirements.in << EOF
          anthropic>=0.60.0
          python-dotenv>=1.0.0
          typing-extensions>=4.0.0
          EOF
          fi

      - name: Update dependencies
        run: |
          pip-compile requirements.in --upgrade
          pip-compile requirements-dev.in --upgrade || echo "No dev requirements file"

      - name: Check for security vulnerabilities
        run: |
          pip install safety
          safety check -r requirements.txt || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: automated dependency update"
          body: |
            ## Automated Dependency Update

            This PR updates project dependencies to their latest compatible versions.

            ### Changes
            - Updated dependencies in requirements.txt
            - Ran security check with safety

            ### Testing
            Please verify that all tests pass and the application works correctly with the updated dependencies.

            ---
            *This PR was created automatically by the dependency update workflow.*
          branch: automated/dependency-update
          delete-branch: true
          labels: |
            dependencies
            automated-pr
